from __future__ import annotations
from typing import Protocol


class CollectionProtocol(Protocol):
    async def find(self, _filter) -> list[dict]: ...
    async def insert(self, _object) -> None: ...
    async def update(self, _filter, _object) -> None: ...
    async def delete(self, _filter) -> None: ...
    async def pop(self, _filter) -> dict: ...


class ConnectionProtocol(Protocol):
    async def __aenter__(self) -> ConnectionProtocol: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def __getattr__(self, key) -> CollectionProtocol: ...
    def commit(self) -> None: ...
    def collections(self) -> tuple[CollectionProtocol]: ...
